name: Build Main # Release Version

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: maven

      - name: Build and Test SNAPSHOT
        run: mvn -B clean package test --file pom.xml

      #- name: Increment Version
      #  run: |
      #    mvn build-helper:parse-version versions:set -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.incrementalVersion} versions:commit
      #    git config user.name "Jumin Rubin"
      #    git config user.email juminrubin@gmail.com
      #    git add .
      #    git commit -m "updated version in pom.xml"
      #    git push
#
#      - name: Create Git Tag
#        run: |
#          export version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
#          git config user.name "Jumin Rubin"
#          git config user.email juminrubin@gmail.com
#          git tag -a v$version -m "v$version"
#          git push origin $version
#
#      - name: Build release version with Maven
#        run: mvn -B clean package --file pom.xml
#        
#      - name: Deploy to GitHub repo
#        run: mvn --batch-mode -DuseGitHubPackages=true deploy
#        env:
#          GITHUB_TOKEN: ${{ secrets.DEPLOY_GITHUB_TOKEN }}
